# Generated by Django 5.0.6 on 2026-09-04 15:08

import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        unique=True,
                        validators=[apps.accounts.validators.validate_indian_phone],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Retail Customer"),
                            ("WHOLESALE_PENDING", "Wholesale Customer (Pending Verification)"),
                            ("WHOLESALE_APPROVED", "Wholesale Customer (Approved)"),
                            ("STAFF", "Operations Staff"),
                            ("MANAGER", "Operations Manager"),
                            ("SUPERADMIN", "Super Administrator"),
                        ],
                        db_index=True,
                        default="CUSTOMER",
                        max_length=25,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, validators=[apps.accounts.validators.validate_indian_phone]
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, default="", max_length=255)),
                ("landmark", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CG", "Chhattisgarh"),
                            ("DN", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OD", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        max_length=6, validators=[apps.accounts.validators.validate_pincode]
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("WORK", "Work / Commercial"),
                            ("BILLING", "Billing Office"),
                            ("WAREHOUSE", "Warehouse / Facility"),
                        ],
                        default="HOME",
                        max_length=20,
                    ),
                ),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("is_default_billing", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default_shipping", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WholesaleProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "gstin",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        validators=[apps.accounts.validators.validate_gstin],
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        validators=[apps.accounts.validators.validate_pan],
                    ),
                ),
                ("fssai_license", models.CharField(blank=True, default="", max_length=14)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("RETAILER", "Retail Store / Supermarket"),
                            ("HORECA", "Hotel / Restaurant / Cafe"),
                            ("DISTRIBUTOR", "Distributor / Wholesaler"),
                            ("OTHER", "Other Enterprise"),
                        ],
                        default="RETAILER",
                        max_length=30,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wholesale_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_wholesale_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wholesale Profile",
                "verbose_name_plural": "Wholesale Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default_shipping", True)),
                fields=("user",),
                name="unique_default_shipping_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default_billing", True)),
                fields=("user",),
                name="unique_default_billing_per_user",
            ),
        ),
    ]
