# Generated by Django 5.0.6 on 2026-09-06 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_has_exactly_one_owner",
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest_token__isnull", True), ("user__isnull", False)),
                    models.Q(
                        ("guest_token__gt", ""),
                        ("guest_token__isnull", False),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cart_has_exactly_one_owner",
            ),
        ),
    ]
