# Generated by Django 5.0.6 on 2026-09-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_cart_has_exactly_one_owner_and_more"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="promotions.coupon",
            ),
        ),
    ]
