# Generated by Django 5.0.6 on 2026-09-06 16:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0002_creditnotesequence_invoice_status_creditnote_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("return_number", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Staff Review"),
                            ("APPROVED", "Approved for Pickup"),
                            ("REJECTED", "Rejected"),
                            ("PICKUP_SCHEDULED", "Reverse Pickup Scheduled"),
                            ("IN_TRANSIT", "In Transit to Warehouse"),
                            ("RECEIVED", "Received at Warehouse"),
                            ("INSPECTED", "Inspection Completed"),
                            ("COMPLETED", "Completed (Resolved)"),
                            ("CANCELLED", "Cancelled by Customer"),
                        ],
                        db_index=True,
                        default="PENDING_REVIEW",
                        max_length=30,
                    ),
                ),
                (
                    "requested_resolution",
                    models.CharField(
                        choices=[
                            ("REFUND", "Monetary Refund & GST Credit Note"),
                            ("REPLACEMENT", "Free Replacement Shipment"),
                        ],
                        default="REFUND",
                        max_length=20,
                    ),
                ),
                (
                    "approved_resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REFUND", "Monetary Refund & GST Credit Note"),
                            ("REPLACEMENT", "Free Replacement Shipment"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED_IN_TRANSIT", "Damaged in Transit / Crushed Packaging"),
                            ("DEFECTIVE_QUALITY", "Quality Defect / Moisture / Aroma Loss"),
                            ("WRONG_ITEM_DELIVERED", "Wrong Item / Variant Delivered"),
                            ("TAMPERED_SEAL", "Tampered Safety Seal / Broken Seal"),
                            ("EXPIRED_OR_NEAR_EXPIRY", "Expired or Close to Expiry Date"),
                            ("MISSING_ITEMS", "Missing Items / Shortage in Package"),
                            ("OTHER", "Other (Requires Staff Review)"),
                        ],
                        default="DEFECTIVE_QUALITY",
                        max_length=35,
                    ),
                ),
                ("customer_notes", models.TextField(blank=True, default="")),
                ("staff_review_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("refund_transaction_id", models.CharField(blank=True, default="", max_length=100)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credit_note",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_return_request",
                        to="invoices.creditnote",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "replacement_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_for_return",
                        to="orders.order",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAMAGED_IN_TRANSIT", "Damaged in Transit / Crushed Packaging"),
                            ("DEFECTIVE_QUALITY", "Quality Defect / Moisture / Aroma Loss"),
                            ("WRONG_ITEM_DELIVERED", "Wrong Item / Variant Delivered"),
                            ("TAMPERED_SEAL", "Tampered Safety Seal / Broken Seal"),
                            ("EXPIRED_OR_NEAR_EXPIRY", "Expired or Close to Expiry Date"),
                            ("MISSING_ITEMS", "Missing Items / Shortage in Package"),
                            ("OTHER", "Other (Requires Staff Review)"),
                        ],
                        default="",
                        max_length=35,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order_line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderlineitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed Quality Inspection"),
                            ("FAILED", "Failed Quality Inspection"),
                            ("SCRAP_DAMAGED", "Authentic Defect / Food Safety Scrap"),
                        ],
                        db_index=True,
                        default="PASSED",
                        max_length=20,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock into Saleable Physical Inventory"),
                            ("DISCARD", "Write-Off / Discard as Unsaleable Scrap"),
                            ("RETURN_TO_CUSTOMER", "Reject & Return to Customer"),
                        ],
                        db_index=True,
                        default="RESTOCK",
                        max_length=30,
                    ),
                ),
                ("quantity_passed", models.PositiveIntegerField(default=0)),
                ("quantity_failed", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("inspected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file_url", models.URLField(blank=True, default="", max_length=500)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnShipment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("shipment_number", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "courier_name",
                    models.CharField(
                        choices=[
                            ("DELHIVERY", "Delhivery"),
                            ("BLUEDART", "Blue Dart"),
                            ("SHIPROCKET", "Shiprocket"),
                            ("INDIAPOST", "India Post"),
                            ("MANUAL", "Manual / Internal Fleet"),
                        ],
                        db_index=True,
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                (
                    "awb_number",
                    models.CharField(blank=True, db_index=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Pickup Scheduled"),
                            ("OUT_FOR_PICKUP", "Out for Pickup"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit to Warehouse"),
                            ("DELIVERED", "Delivered to Warehouse"),
                            ("FAILED_PICKUP", "Failed Pickup"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=30,
                    ),
                ),
                ("scheduled_pickup_date", models.DateField(blank=True, null=True)),
                ("actual_pickup_date", models.DateTimeField(blank=True, null=True)),
                ("received_at_warehouse", models.DateTimeField(blank=True, null=True)),
                ("pickup_recipient_name", models.CharField(max_length=100)),
                ("pickup_phone_number", models.CharField(max_length=15)),
                ("pickup_address_line_1", models.CharField(max_length=255)),
                ("pickup_address_line_2", models.CharField(blank=True, default="", max_length=255)),
                ("pickup_landmark", models.CharField(blank=True, default="", max_length=100)),
                ("pickup_city", models.CharField(max_length=100)),
                ("pickup_state", models.CharField(max_length=50)),
                ("pickup_pincode", models.CharField(max_length=6)),
                ("tracking_notes", models.TextField(blank=True, default="")),
                (
                    "return_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reverse_shipment",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["order", "-created_at"], name="returns_ret_order_i_d0d16c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["user", "-created_at"], name="returns_ret_user_id_655bc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="returns_ret_status_6a52e1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="return_item_quantity_positive"
            ),
        ),
    ]
