# Generated by Django 5.0.6 on 2026-09-06 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNoteSequence",
            fields=[
                (
                    "financial_year",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Credit Note Sequence",
                "verbose_name_plural": "Credit Note Sequences",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("CREDIT_NOTED", "Credit Noted"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("credit_note_number", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "credit_note_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("financial_year", models.CharField(db_index=True, max_length=10)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ORDER_CANCELLATION", "Order Cancelled Post-Invoicing"),
                            ("RETURN_TO_ORIGIN", "Courier Undelivered / Return to Origin"),
                            ("CUSTOMER_RETURN", "Customer Return / Defective Goods"),
                            ("PRICE_ADJUSTMENT", "Post-Sale Price Adjustment / Discount"),
                        ],
                        db_index=True,
                        default="ORDER_CANCELLATION",
                        max_length=30,
                    ),
                ),
                ("reason_notes", models.TextField(blank=True, default="")),
                ("seller_name", models.CharField(max_length=200)),
                ("seller_gstin", models.CharField(max_length=15)),
                ("seller_fssai", models.CharField(max_length=20)),
                ("seller_address", models.TextField()),
                (
                    "seller_state",
                    models.CharField(
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CG", "Chhattisgarh"),
                            ("DN", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OD", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        default="KA",
                        max_length=50,
                    ),
                ),
                ("buyer_name", models.CharField(max_length=150)),
                ("buyer_email", models.CharField(max_length=150)),
                ("buyer_phone", models.CharField(max_length=15)),
                ("buyer_company_name", models.CharField(blank=True, default="", max_length=200)),
                ("buyer_gstin", models.CharField(blank=True, default="", max_length=15)),
                ("buyer_pan", models.CharField(blank=True, default="", max_length=10)),
                ("shipping_address", models.TextField()),
                (
                    "place_of_supply",
                    models.CharField(
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CG", "Chhattisgarh"),
                            ("DN", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OD", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("is_interstate", models.BooleanField(db_index=True, default=False)),
                ("is_b2b", models.BooleanField(db_index=True, default=False)),
                ("items_subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("taxable_subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="credit_notes/%Y/")),
                ("pdf_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="orders.order",
                    ),
                ),
                (
                    "original_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-credit_note_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditNoteLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("variant_name", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=64)),
                ("hsn_code", models.CharField(db_index=True, max_length=10)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("taxable_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gst_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cgst_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "igst_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoices.creditnote",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_lines",
                        to="invoices.invoicelineitem",
                    ),
                ),
                (
                    "order_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_lines",
                        to="orders.orderlineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["credit_note_number"], name="invoices_cr_credit__3ed54b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["credit_note_date", "-created_at"], name="invoices_cr_credit__98c83b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(fields=["order", "reason"], name="invoices_cr_order_i_cc7e70_idx"),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                check=models.Q(("grand_total__gte", 0)), name="credit_note_grand_total_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="credit_note_line_quantity_positive"
            ),
        ),
    ]
