# Generated by Django 5.0.6 on 2026-09-06 17:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_creditnotesequence_invoice_status_creditnote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Order-level discount deducted from invoice gross value.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Allocated discount for this line item.",
                max_digits=10,
            ),
        ),
    ]
