# Generated by Django 5.0.6 on 2026-09-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_total_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PARTIALLY_CREDIT_NOTED", "Partially Credit Noted"),
                    ("CREDIT_NOTED", "Credit Noted"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=30,
            ),
        ),
    ]
