# Generated by Django 5.0.6 on 2026-09-07 14:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "promo_type",
                    models.CharField(
                        choices=[
                            ("ORDER_DISCOUNT", "Order Level Discount"),
                            ("BUY_X_GET_Y", "Buy X Get Y"),
                            ("CATEGORY_DISCOUNT", "Category Discount"),
                            ("FREE_SHIPPING", "Free Shipping"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("FIXED_AMOUNT", "Fixed Amount")],
                        max_length=20,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_order_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Evaluation precedence: lower values evaluate first."
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_to_wholesale",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this promotion applies to wholesale/B2B tier customers.",
                    ),
                ),
                (
                    "stackable_with_coupons",
                    models.BooleanField(
                        default=True,
                        help_text="Whether customer coupons can be combined on top of this automatic promotion.",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum required item quantity for this rule to trigger.",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("FIXED_AMOUNT", "Fixed Amount")],
                        max_length=20,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_order_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                (
                    "usage_limit_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum global redemptions allowed across all customers.",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum redemptions allowed per individual customer account.",
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_to_wholesale",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this coupon can be combined with wholesale contract pricing.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ORDER", "Entire Order"),
                            ("CATEGORY", "Specific Categories"),
                            ("PRODUCT", "Specific Products/Variants"),
                        ],
                        default="ORDER",
                        max_length=20,
                    ),
                ),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.category"
                    ),
                ),
                (
                    "applicable_variants",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.productvariant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("discount_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDiscountSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("discount_name", models.CharField(max_length=255)),
                ("discount_type", models.CharField(max_length=20)),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("applied_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statutory_gst_adjusted",
                    models.BooleanField(
                        default=True,
                        help_text="Affirms discount reduces GST taxable consideration under Section 15(3) CGST Act.",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_snapshots",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_snapshots",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_value__gt", Decimal("0.00"))),
                name="promotion_discount_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                check=models.Q(("min_order_value__gte", Decimal("0.00"))),
                name="promotion_min_order_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                check=models.Q(("valid_to__gt", models.F("valid_from"))),
                name="promotion_valid_to_after_valid_from",
            ),
        ),
        migrations.AddField(
            model_name="orderdiscountsnapshot",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_snapshots",
                to="promotions.promotion",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="promotions.promotion",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_rules",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="target_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_rules",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_value__gt", Decimal("0.00"))),
                name="coupon_discount_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("min_order_value__gte", Decimal("0.00"))),
                name="coupon_min_order_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("valid_to__gt", models.F("valid_from"))),
                name="coupon_valid_to_after_valid_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("times_used__gte", 0)), name="coupon_times_used_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)),
                fields=("coupon", "order"),
                name="unique_coupon_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_amount__gte", Decimal("0.00"))),
                name="coupon_usage_discount_positive",
            ),
        ),
    ]
