# Generated by Django 5.0.6 on 2026-09-06 15:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_refunded",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_transaction_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100),
        ),
    ]
