# Generated by Django 5.0.6 on 2026-09-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_amount_refunded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AUTHORIZED", "Authorized"),
                    ("CAPTURED", "Captured"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AUTHORIZED", "Authorized"),
                    ("CAPTURED", "Captured"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("REFUNDED", "Refunded"),
                ],
                max_length=30,
            ),
        ),
    ]
