# Generated by Django 5.0.6 on 2026-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_status_alter_paymentattempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Customer-uploaded UPI payment confirmation screenshot",
                null=True,
                upload_to="payments/screenshots/",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="utr_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Customer-submitted 12-digit UPI UTR / RRN transaction reference number",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("MANUAL", "Manual / Offline"),
                    ("PHONEPE_QR", "PhonePe UPI QR"),
                ],
                db_index=True,
                default="RAZORPAY",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PENDING_VERIFICATION", "Pending Verification"),
                    ("AUTHORIZED", "Authorized"),
                    ("CAPTURED", "Captured"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PENDING_VERIFICATION", "Pending Verification"),
                    ("AUTHORIZED", "Authorized"),
                    ("CAPTURED", "Captured"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("REFUNDED", "Refunded"),
                ],
                max_length=30,
            ),
        ),
    ]
