# Generated by Django 5.0.6 on 2026-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_payment_screenshot_payment_utr_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("MANUAL", "Manual / Offline"),
                    ("PHONEPE_QR", "PhonePe UPI QR"),
                    ("COD", "Cash on Delivery"),
                ],
                db_index=True,
                default="RAZORPAY",
                max_length=30,
            ),
        ),
    ]
