# Generated by Django 5.0.6 on 2026-09-05 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
                ("quantity_reserved", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_item",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["variant__sku"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INBOUND", "Inbound stock"),
                            ("SALE", "Sale"),
                            ("RESERVATION", "Reservation"),
                            ("CANCELLATION", "Reservation cancellation"),
                            ("EXPIRY", "Reservation expiry"),
                            ("ADJUSTMENT", "Stock adjustment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "quantity_delta",
                    models.IntegerField(
                        help_text="Physical quantity-on-hand change; zero for pure reservation events."
                    ),
                ),
                (
                    "reserved_quantity_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Reserved allocation change; zero for pure physical stock events.",
                    ),
                ),
                ("reference_type", models.CharField(blank=True, default="", max_length=30)),
                ("reference_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Future owner type, such as CART or ORDER; deliberately not a foreign key.",
                        max_length=30,
                    ),
                ),
                ("reference_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RELEASED", "Released"),
                            ("CONSUMED", "Consumed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity_on_hand__gte", 0)), name="inventory_on_hand_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity_reserved__gte", 0)),
                name="inventory_reserved_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity_on_hand__gte", models.F("quantity_reserved"))),
                name="inventory_reserved_not_above_on_hand",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["stock_item", "created_at"], name="inventory_s_stock_i_c40196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"], name="inventory_s_movemen_ed5291_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["status", "expires_at"], name="inventory_s_status_c656ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["stock_item", "status"], name="inventory_s_stock_i_dee0fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="inventory_reservation_quantity_positive"
            ),
        ),
    ]
