# Generated by Django 5.0.6 on 2026-09-06 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("shipment_number", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("LABEL_GENERATED", "Label Generated"),
                            ("READY_FOR_PICKUP", "Ready for Pickup"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED_DELIVERY", "Failed Delivery"),
                            ("RETURNED_TO_ORIGIN", "Returned to Origin (RTO)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "courier_name",
                    models.CharField(
                        choices=[
                            ("DELHIVERY", "Delhivery"),
                            ("BLUEDART", "Blue Dart"),
                            ("SHIPROCKET", "Shiprocket"),
                            ("INDIAPOST", "India Post"),
                            ("MANUAL", "Manual / Internal Fleet"),
                        ],
                        db_index=True,
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                (
                    "awb_number",
                    models.CharField(blank=True, db_index=True, default="", max_length=100),
                ),
                ("shipping_label_url", models.URLField(blank=True, default="", max_length=500)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "weight_in_grams",
                    models.PositiveIntegerField(
                        help_text="Total package physical or volumetric weight in grams."
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "breadth_cm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "height_cm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("shipping_recipient_name", models.CharField(max_length=100)),
                ("shipping_phone_number", models.CharField(max_length=15)),
                ("shipping_address_line_1", models.CharField(max_length=255)),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("shipping_landmark", models.CharField(blank=True, default="", max_length=100)),
                ("shipping_city", models.CharField(db_index=True, max_length=100)),
                (
                    "shipping_state",
                    models.CharField(
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CG", "Chhattisgarh"),
                            ("DN", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OD", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("shipping_pincode", models.CharField(db_index=True, max_length=6)),
                ("notes", models.TextField(blank=True, default="")),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order_line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_items",
                        to="orders.orderlineitem",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("LABEL_GENERATED", "Label Generated"),
                            ("READY_FOR_PICKUP", "Ready for Pickup"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED_DELIVERY", "Failed Delivery"),
                            ("RETURNED_TO_ORIGIN", "Returned to Origin (RTO)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=150)),
                ("description", models.CharField(max_length=500)),
                ("event_timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["order", "-created_at"], name="shipping_sh_order_i_a287c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "-created_at"], name="shipping_sh_status_8a7968_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["awb_number"], name="shipping_sh_awb_num_33ed04_idx"),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.CheckConstraint(
                check=models.Q(("weight_in_grams__gt", 0)), name="shipment_weight_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="shipment_item_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentitem",
            constraint=models.UniqueConstraint(
                fields=("shipment", "order_line_item"), name="unique_shipment_line_item"
            ),
        ),
    ]
