# Generated by Django 5.0.6 on 2026-09-04 17:39

import apps.catalog.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.validators.category_image_upload_path,
                        validators=[apps.catalog.validators.validate_image_file],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[("RESERVE", "Reserve Tier"), ("EVERYDAY", "Everyday Fresh")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("WHOLE", "Whole Spice"),
                            ("GROUND", "Ground / Powdered"),
                            ("BLEND", "Signature Blend"),
                            ("RAW", "Raw / Whole Nut / Dry Fruit"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("short_description", models.CharField(blank=True, default="", max_length=500)),
                ("detailed_description", models.TextField(blank=True, default="")),
                (
                    "origin_region",
                    models.CharField(
                        db_index=True, default="Malenadu, Karnataka, India", max_length=150
                    ),
                ),
                (
                    "plantation_provenance",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Family plantation history and valley micro-climate notes.",
                    ),
                ),
                (
                    "origin_stamp",
                    models.CharField(default="Grown in Malenadu · Uttara Kannada", max_length=200),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Bold 8mm+, Grade A Export Quality",
                        max_length=100,
                    ),
                ),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("grinding_date", models.DateField(blank=True, null=True)),
                (
                    "sharada_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Spoken narrative in Sharada's voice: culinary advice and flavor memories.",
                    ),
                ),
                (
                    "qr_audio_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Direct link to customer-accessible QR folklore audio snippet.",
                    ),
                ),
                (
                    "fssai_license",
                    models.CharField(blank=True, default="11223344556677", max_length=20),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        db_index=True,
                        help_text="Statutory GST Harmonized System of Nomenclature code (e.g. 0904, 0801).",
                        max_length=10,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Applicable GST percentage (e.g. 5.00 or 12.00).",
                        max_digits=5,
                    ),
                ),
                (
                    "packer_name",
                    models.CharField(default="Bharath Masala Products", max_length=200),
                ),
                (
                    "packer_address",
                    models.TextField(
                        default="Main Road, Thirthahalli, Shimoga District, Karnataka 577432"
                    ),
                ),
                (
                    "best_before_guidance",
                    models.CharField(
                        default="Best before 12 months from packing date", max_length=150
                    ),
                ),
                ("is_bestseller", models.BooleanField(db_index=True, default=False)),
                (
                    "is_featured_from_home",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Highlight in homepage 'From home' Reserve collection showcase.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.validators.product_image_upload_path,
                        validators=[apps.catalog.validators.validate_image_file],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, default="", max_length=200)),
                ("is_hero", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["-is_hero", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("review_body", models.TextField()),
                ("verified_purchase", models.BooleanField(default=False)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Moderation"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("variant_name", models.CharField(max_length=100)),
                ("sku", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "weight_in_grams",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Net weight in grams for shipping and legal metrology.",
                        null=True,
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum Retail Price printed on pack.",
                        max_digits=10,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Offered retail price (must be <= MRP).",
                        max_digits=10,
                    ),
                ),
                (
                    "is_most_chosen",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag for highlighting the most popular pack size in the UI.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["sort_order", "selling_price"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.validators.review_image_upload_path,
                        validators=[apps.catalog.validators.validate_image_file],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Image",
                "verbose_name_plural": "Review Images",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="WholesaleTierPricing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        help_text="Minimum order quantity threshold for this price tier."
                    ),
                ),
                (
                    "wholesale_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax-exclusive wholesale price per unit.",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wholesale_slabs",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wholesale Tier Pricing",
                "verbose_name_plural": "Wholesale Tier Pricing Slabs",
                "ordering": ["min_quantity"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="catalog_pro_categor_891fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["tier", "is_active"], name="catalog_pro_tier_48eb50_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured_from_home", "is_active"], name="catalog_pro_is_feat_3ce0bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_bestseller", "is_active"], name="catalog_pro_is_best_de7c4e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_hero", True)),
                fields=("product",),
                name="unique_active_hero_image_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "moderation_status"], name="catalog_pro_product_a21e04_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="check_review_rating_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="unique_review_per_user_product"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active", "sort_order"], name="catalog_pro_product_633092_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                check=models.Q(("selling_price__lte", models.F("mrp"))),
                name="check_variant_selling_price_lte_mrp",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                check=models.Q(("selling_price__gt", 0)), name="check_variant_selling_price_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                check=models.Q(("mrp__gt", 0)), name="check_variant_mrp_gt_zero"
            ),
        ),
        migrations.AddIndex(
            model_name="wholesaletierpricing",
            index=models.Index(
                fields=["variant", "min_quantity"], name="catalog_who_variant_b97588_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wholesaletierpricing",
            constraint=models.UniqueConstraint(
                fields=("variant", "min_quantity"), name="unique_wholesale_variant_slab"
            ),
        ),
        migrations.AddConstraint(
            model_name="wholesaletierpricing",
            constraint=models.CheckConstraint(
                check=models.Q(("wholesale_price_per_unit__gt", 0)),
                name="check_wholesale_price_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="wholesaletierpricing",
            constraint=models.CheckConstraint(
                check=models.Q(("min_quantity__gte", 1)),
                name="check_wholesale_min_quantity_gte_one",
            ),
        ),
    ]
