# Generated by Django 5.0.6 on 2026-09-06 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_target", models.CharField(db_index=True, max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("WHATSAPP", "WhatsApp"), ("SMS", "SMS")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ORDER_CONFIRMED", "Order Confirmed"),
                            ("ORDER_PROCESSING", "Order Processing"),
                            ("ORDER_SHIPPED", "Order Shipped"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="orders.order",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "status"], name="notificatio_channel_f70f70_idx"
                    ),
                    models.Index(
                        fields=["event", "-created_at"], name="notificatio_event_b2abc2_idx"
                    ),
                    models.Index(
                        fields=["recipient_target", "-created_at"],
                        name="notificatio_recipie_1ffb87_idx",
                    ),
                ],
            },
        ),
    ]
