# Generated by Django 5.0.6 on 2026-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("ORDER_CONFIRMED", "Order Confirmed"),
                    ("ORDER_PROCESSING", "Order Processing"),
                    ("ORDER_SHIPPED", "Order Shipped"),
                    ("ORDER_DELIVERED", "Order Delivered"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("REFUND_PROCESSED", "Refund Processed"),
                    ("CREDIT_NOTE_ISSUED", "Credit Note Issued"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
